name: GaroK
favicon: null
layout_spectrum: 0.7671026019379497
typography_spectrum: 0.13710059341974556
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.44621056597679853
  lightness: 0.405328479828313
  saturation: 0.5224007696378976
  rhythmicContrast: 0.9264316277112812
purpose: []
